apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ixidod/devops-go
    path: /
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
