apiVersion: apps/v1

kind: Deployment

metadata:
  name: demo-go
  labels:
    app: demo-go
    #spec spec spec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
        - name: demo-go
          image: zavulon/devops-goslim:70be15a4b121a901166fb5703de474a777b341d0
          ports:
            - containerPort: 8080
